### ISSUE TITLE
Release dataset on Hugging Face

### ISSUE THREAD

**Issue by NielsRogge** [hshjerry/VideoEspresso#1]
Hello @hshjerry 🤗

I'm Niels and work as ML engineer at Hugging Face. I discovered your work as it got featured in Hugging Face's daily papers: https://huggingface.co/papers/2411.14794. The paper page lets people discuss about your paper and lets them find artifacts about it (your dataset for instance) you can also claim the paper as yours which will show up on your public profile at HF.

Would you like to host the datasets on https://huggingface.co/datasets? Hosting on Hugging Face will give you more visibility, and will also allow people to do:

```python
from datasets import load_dataset

dataset = load_dataset("your-hf-org/yes-but")
```

If you're down, leaving a guide here: https://huggingface.co/docs/datasets/main/en/video_load. We also support Webdataset, useful for image/video datasets: https://huggingface.co/docs/datasets/en/loading#webdataset.

Besides that, there's the [dataset viewer](https://huggingface.co/docs/hub/en/datasets-viewer) which allows people to quickly explore the first few rows of the data in the browser.

After uploaded, we can also link the datasets to the paper page (read [here](https://huggingface.co/docs/hub/en/model-cards#linking-a-paper)) so people can discover your work.

What do you think?

Kind regards,

Niels

**Comment by hshjerry** [comment]
Dear @NielsRogge, thank you for your comment. We will upload dataset as soon as possible on huggingface. :)

**Comment by NielsRogge** [comment]
Thank you, would it be possible to keep this issue open so that we can track it?

**Comment by hshjerry** [comment]
Sure, I have reopened the issue. 😊

**Comment by xiaoqian-shen** [comment]
Hi @hshjerry,

I am not able to extract the zip file after combining all zip parts from [Train Set (Video)](https://huggingface.co/datasets/hshjerry0315/VideoEspresso_train_video/tree/main). Could you share the command for combining them and double check whether it is extractable? Sincerely appreciate your help.

**Comment by NielsRogge** [comment]
To upload the videos to the hub, refer to this guide: https://huggingface.co/docs/datasets/en/video_load

**Comment by Imran-tech-lab** [comment]
@hshjerry i can help you to reformate the dataset with chat format like this

```{
  "messages": [
    {
      "role": "user",
      "content": "<video>Did the green cube slide off the ramp and land in the box?"
    },
    {
      "role": "assistant",
      "content": "<think>The green cube starts at the top of the ramp and begins sliding. Observing frame-by-frame, it maintains momentum, reaches the end of the ramp, and falls into the box.</think>[{\"description\": \"Green cube lands inside box.\", \"start_time\": \"0:02\", \"end_time\": \"0:07\", \"event\": \"Landing\"}]"
    }
  ],
  "videos": ["/data/green_cube_ramp_001.mp4"]
}
```
